services:
 
  frontend:
    image: ${ECR_REGISTRY}/hello-app-frontend:${IMAGE_TAG}
    ports:
      - "5173:5173"
    depends_on:
      - backend
 
  backend:
    image: ${ECR_REGISTRY}/hello-app-backend:${IMAGE_TAG}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
 
  mongodb:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
 
volumes:
  mongo_data: