name: Hello App CI/CD
defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      commit_id: ${{ github.sha }}
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}
      MONGO_ROOT_USER: ${{ secrets.MONGO_ROOT_USER }}
      MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}


